# Generated by Django 2.2.6 on 2020-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_auto_20200210_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(max_length=1000),
        ),
    ]
